#pragma once

#define MASTER_RIGHT

#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_LED GP17
#define RP2040_BOOTLOADER_DOUBLE_TAP_RESET_TIMEOUT 1000U
#define UNICODE_SELECTED_MODES UNICODE_MODE_LINUX

#define SPI_DRIVER SPID1
#define SPI_SCK_PIN GP10
#define SPI_MISO_PIN GP12
#define SPI_MOSI_PIN GP11
#define POINTING_DEVICE_CS_PIN GP13
#define ROTATIONAL_TRANSFORM_ANGLE -45
#define POINTING_DEVICE_INVERT_X true
#define PMW33XX_CPI 600
